//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ADProLED.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_ZOOM_RTIME                   101
#define ID_ZOOM_PREV                    102
#define ID_ZOOM_WINDOW                  103
#define ID_ZOOM_EXT                     104
#define ID_ZOOM_IN                      105
#define ID_ZOOM_OUT                     106
#define ID_PAN_RTIME                    107
#define ID_PAN_POINT                    108
#define ID_3DVIEWS_TOP                  109
#define ID_3DVIEWS_BOTTOM               110
#define ID_3DVIEWS_LEFT                 111
#define ID_3DVIEWS_RIGHT                112
#define ID_3DVIEWS_FRONT                113
#define ID_3DVIEWS_BACK                 114
#define ID_3DVIEWS_SWISOMETRIC          115
#define ID_3DVIEWS_SEISOMETRIC          116
#define ID_3DVIEWS_NEISOMETRIC          117
#define ID_3DVIEWS_NWISOMETRIC          118
#define ID_3DVIEWS_VIEWPOINTPRESETS     119
#define IDR_MAINFRAME                   128
#define IDR_ADPROLEDTYPE                129
#define IDD_LOGIN                       130
#define IDR_DRAW                        134
#define IDR_EDIT                        136
#define IDB_FORMAT                      139
#define IDB_DIM                         140
#define IDD_LEDTEXT_DLG                 141
#define IDD_NODETEXT_DLG                141
#define IDR_SNAP                        142
#define IDB_RED                         143
#define IDB_BLUE                        144
#define IDC_CUR_TEXT                    146
#define IDD_CALC_DLG                    149
#define IDD_SET_PAYMENT_DLG             150
#define CB_LAYERS                       153
#define CB_COLORS                       154
#define CB_LTYPES                       155
#define CB_LWEIGHTS                     156
#define CB_DIMS                         157
#define IDC_EDIT_USER                   1000
#define IDC_EDIT_PASSWORD               1001
#define IDC_EDIT_TEXT                   1004
#define IDC_PREVIEW_TEXT                1005
#define IDC_LIST_FONT_FACE              1006
#define IDC_LIST_FONT_STYLE             1007
#define IDC_LIST_FONT_SIZE              1008
#define IDC_EDIT_FONT_FACE              1012
#define IDC_EDIT_FONT_SIZE              1013
#define IDC_EDIT_FONT_STYLE             1014
#define IDC_EDIT_NUDE_SIZE              1015
#define IDC_EDIT_NODE_SIZE              1015
#define IDC_EDIT_NUDE_DISTANCE          1016
#define IDC_EDIT_NODE_DISTANCE          1016
#define IDC_EDIT_NODE_SPACE             1016
#define IDC_EDIT_NUDE_SCALE             1017
#define IDC_EDIT_X                      1017
#define IDC_SPIN_NODE_SIZE              1018
#define IDC_SPIN_NODE_DISTANCE          1019
#define IDC_SPIN_NODE_SPACE             1019
#define IDC_EDIT_Y                      1021
#define IDC_EDIT_LED_SIZE               1022
#define IDC_EDIT_Z                      1023
#define IDC_EDIT_PX                     1023
#define IDC_SPIN_Z                      1024
#define IDC_EDIT_PY                     1024
#define IDC_EDIT_DX                     1025
#define IDC_EDIT_DY                     1026
#define IDC_COMBO_LED_SIZE              1027
#define IDC_COMBO_NODE_SIZE             1027
#define IDC_BUTTON_CALC                 1028
#define IDC_EDIT_TITLE_NODE             1029
#define IDC_EDIT_TOTAL_NODE             1030
#define IDC_EDIT_TITLE_RED3             1031
#define IDC_EDIT_TOTAL_RED3             1032
#define IDC_EDIT_TITLE_RED5             1033
#define IDC_EDIT_TOTAL_RED5             1034
#define IDC_EDIT_TITLE_BLUE3            1035
#define IDC_EDIT_TOTAL_BLUE3            1036
#define IDC_EDIT_TITLE_BLUE5            1037
#define IDC_EDIT_TOTAL_BLUE5            1038
#define IDC_EDIT_TITLE_GREEN3           1039
#define IDC_EDIT_TOTAL_GREEN3           1040
#define IDC_EDIT_TITLE_GREEN5           1041
#define IDC_EDIT_TOTAL_GREEN5           1042
#define IDC_EDIT_TITLE_WHITE3           1043
#define IDC_EDIT_TOTAL_WHITE3           1044
#define IDC_EDIT_TITLE_OTHER            1045
#define IDC_EDIT_TOTAL_OTHER            1046
#define IDC_EDIT_TITLE_CPU              1047
#define IDC_EDIT_TOTAL_CPU              1048
#define IDC_EDIT_TITLE_POWER            1049
#define IDC_EDIT_TOTAL_POWER            1050
#define IDC_EDIT_TITLE_CASE             1051
#define IDC_EDIT_TOTAL_CASE             1052
#define IDC_EDIT_TITLE_EXTRA            1053
#define IDC_EDIT_TOTAL_EXTRA            1054
#define IDC_EDIT_TITLE_TOTAL            1055
#define IDC_EDIT_TOTAL_PAY              1056
#define ID_FILE_PRINTPREVIEW            32771
#define ID_FILE_RECENT                  32772
#define ID_PREVIEW_EXIT                 32776
#define ID_PREVIEW_PRINT                32777
#define ID_FMT_LINEWEIGHT               32778
#define ID_FMT_TEXTSTYLE                32779
#define ID_TOOL_DISTANCE                32780
#define ID_TOOL_AREA                    32781
#define ID_TOOL_OPTIONS                 32782
#define ID_FMT_PAGE                     32783
#define ID_FMT_LAYER                    32785
#define ID_FMT_LINETYPE                 32786
#define ID_TOOL_CALIBRATE               32787
#define ID_TOOL_DWGINFO                 32788
#define ID_TOOL_CMDLINE                 32790
#define ID_DRAW_LINE                    32791
#define ID_DRAW_HATCH                   32792
#define ID_EDIT_MOVE                    32795
#define ID_DRAW_CIRC_CR                 32797
#define ID_EDIT_ROTATE                  32798
#define ID_EDIT_ERASE                   32799
#define ID_EDIT_PROP                    32800
#define ID_EDIT_SCALE                   32802
#define ID_EDIT_MIRROR                  32803
#define ID_EDIT_EXPLODE                 32804
#define ID_EDIT_JOIN                    32805
#define ID_DRAW_RAY                     32806
#define ID_EDIT_XLINE                   32807
#define ID_DRAW_MLINE                   32808
#define ID_DRAW_CIRC_CD                 32809
#define ID_DRAW_CIRC_2P                 32810
#define ID_DRAW_CIRC_3P                 32811
#define ID_DRAW_ARC_3P                  32812
#define ID_DRAW_ARC_SCE                 32814
#define ID_DRAW_ARC_SCA                 32815
#define ID_DRAW_ARC_SCL                 32816
#define ID_DRAW_ARC_SEA                 32817
#define ID_DRAW_ARC_SED                 32818
#define ID_DRAW_ARC_SER                 32819
#define ID_DRAW_ARC_CSE                 32820
#define ID_DRAW_ARC_CSA                 32821
#define ID_DRAW_ARC_CSL                 32822
#define ID_DRAW_ARC_CONTINUE            32823
#define ID_DRAW_ELLIPSE_CENTER          32824
#define ID_DRAW_ELLIPSE_AXIS            32825
#define ID_DRAW_ELLIPSE_ARC             32826
#define ID_DRAW_PLINE                   32827
#define ID_DRAW_POLYGON                 32828
#define ID_DRAW_POLYLINE                32829
#define ID_DRAW_RECT                    32830
#define ID_DRAW_SPLINE                  32831
#define ID_DRAW_MAKEBLOCK               32832
#define ID_DRAW_POINT                   32833
#define ID_DRAW_MPOINT                  32834
#define ID_DRAW_POINT_SINGLE            32835
#define ID_DRAW_POINT_MULTIPLE          32836
#define ID_DRAW_POINT_DIV               32837
#define ID_DRAW_POINT_DIVIDE            32838
#define ID_DRAW_POINT_MEASURE           32839
#define ID_DRAW_SINGLETEXT              32840
#define ID_DRAW_TEXT                    32841
#define ID_INS_BLOCK                    32842
#define ID_INS_EXTERNAL                 32843
#define ID_INS_IMAGE                    32844
#define ID_EDIT_UNSELECT                32845
#define ID_DRAW_MULTI_TEXT              32848
#define ID_FMT_COLOR                    32849
#define ID_REPEAT_LAST                  32850
#define ID_TOOL_AIDS                    32851
#define ID_SHOW_GRID                    32852
#define ID_SNAP_GRID                    32853
#define ID_DRAW_ELLIPSE                 32854
#define ID_PLINE_ENTER                  32855
#define ID_PLINE_CANCEL                 32856
#define ID_PLINE_ENTER_PGON             32858
#define ID_PLINE_UNDO                   32859
#define ID_PLINE_ARC                    32860
#define ID_PLINE_LINE                   32861
#define ID_PLINE_INSVER                 32862
#define ID_PLINE_DELVER                 32863
#define ID_PLINE_BULGE                  32864
#define ID_SPLINE_ENTER                 32866
#define ID_SPLINE_ENTER_CLOSED          32867
#define ID_SPLINE_ENTER_PGON            32868
#define ID_SPLINE_CANCEL                32869
#define ID_SPLINE_UNDO                  32870
#define ID_INS_IMAGE_MANAGER            32871
#define ID_IMPORT_SHP                   32875
#define ID_EXPORT_AVSHP                 32876
#define ID_IMPORT_AVSHP                 32877
#define ID_INS_RASTER_IMG               32879
#define ID_TOOL_SFP                     32880
#define ID_TOOL_AVSHP_LAT               32881
#define ID_TOOL_AVSHP_LONG              32882
#define ID_TOOL_AVSHP_GEN               32883
#define ID_TOOL_AVSHP_INSERT            32884
#define ID_FMT_PNTSTYLE                 32885
#define ID_TOOL_CONVERT                 32886
#define ID_TOOL_INSERT_AVSHP            32887
#define ID_TOOL_CONVERT_TTF_TO_VCF      32888
#define ID_TOOL_CONVERY_SHX_TO_VCF      32889
#define ID_TOOL_INSTALLED_FONT          32890
#define ID_TOOL_MAKE_RASTER             32891
#define ID_TOOL_DRAW_INFO               32892
#define ID_TOOL_CONVERT_COORDINATE      32893
#define ID_TOOL_OPTION                  32894
#define ID_ZOOM_SEL                     32895
#define ID_LAYERS_ORDER                 32896
#define ID_TOOL_VIEW_SETTING            32897
#define ID_PLINE_EDITVER                32898
#define ID_DRAW_XLINE                   32899
#define ID_FMT_MLINESTYLE               32900
#define ID_MLINE_ENTER                  32901
#define ID_MLINE_ENTER_CLOSED           32902
#define ID_MLINE_CANCEL                 32903
#define ID_MLINE_UNDO                   32904
#define ID_SELECT_BY_ID                 32905
#define ID_SELECT_BY_USERDATA           32906
#define ID_TOOL_RASTERIZE               32907
#define ID_SELECT_BY_TEXT               32908
#define ID_SELECT_BY_POINT              32909
#define ID_SELECT_BY_RECTANGLE          32910
#define ID_INS_XREF_MANAGER             32911
#define ID_IMAGE_MANAGER                32912
#define ID_INS_ARCVIEW                  32913
#define ID_SELECT_BY_POLYGON            32914
#define ID_SELECT_BY_POLYLINE           32915
#define ID_SELECT_BY_DISTANCE           32916
#define ID_EDIT_DELETE                  32917
#define ID_EDIT_JOINT                   32918
#define ID_VIEW_PAGE                    32919
#define ID_FORMAT_XREF_MAN              32920
#define ID_TOOL_TTF2VCF                 32921
#define ID_TOOL_SHX2VCF                 32922
#define ID_TOOL_FONTLIST                32923
#define ID_FORMAT_ATT_MAN               32924
#define ID_FORMAT_IMAGE_MAN             32925
#define ID_SNAP_DLG                     32926
#define ID_SNAP_CLEAR                   32927
#define ID_FORMAT_PAGE                  32928
#define ID_SNAP_ENDPOINT                32930
#define ID_SNAP_MIDPOINT                32931
#define ID_SNAP_CENTER                  32932
#define ID_SNAP_POINT                   32933
#define ID_SNAP_INTER                   32934
#define ID_SNAP_PERPEND                 32935
#define ID_SNAP_TANGENT                 32936
#define ID_SNAP_NEAR                    32937
#define ID_SNAP_GRIP                    32938
#define ID_TOOL_GRID                    32941
#define ID_TOOL_POLAR                   32942
#define ID_SNAP_NONE                    32943
#define ID_TOOL_SET_PAYMENT             32943
#define ID_VIEW_BLOCK                   32944
#define ID_FMT_DIMSTYLE                 32945
#define ID_DESIGN_EXPORT2PCB            32946
#define ID_EXPORTTO_PROTELPCB2          32947
#define ID_DIM_LINEAR                   32949
#define ID_DIM_ALIGNED                  32950
#define ID_DIM_ORDINATE                 32951
#define ID_DIM_RADIUS                   32952
#define ID_DIM_DIAM                     32953
#define ID_DIM_ANGULAR                  32954
#define ID_DIM_LEADER                   32955
#define ID_DIM_CMARK                    32956
#define ID_EDIT_TRIM                    32957
#define ID_EDIT_EXTEND                  32958
#define ID_VIEW_MAG                     32960
#define ID_VIEW_AVIEW                   32961
#define ID_BREAK_INTO                   32962
#define ID_INS_ATTDEF                   32963
#define ID_EDIT_ATTRIB                  32964
#define ID_FMT_ATTMAN                   32965
#define ID_TOOL_AREAIP                  32966

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32948
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
