//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MATRIX.rc
//
#define IDS_DEVICE_SAVE_TEXT            1
#define IDS_SAVE_TEXT                   1
#define IDR_MANIFEST                    1
#define IDS_LOAD_TEXT                   2
#define IDS_SAVE_BACKGROUND             3
#define IDS_LOAD_BACKGROUND             4
#define IDS_SAVE_ALL_DATA               5
#define IDS_LOAD_ALL_DATA               6
#define IDS_SAVE_CHARACTER_FONT         7
#define IDS_LOAD_CHARACTER_FONT         8
#define IDS_LOAD_ASCII_TEXT             9
#define IDD_MATRIX_DIALOG               102
#define CG_IDR_POPUP_MATRIX_SIMULATOR   103
#define IDR_MAINFRAME                   128
#define IDR_MENU                        131
#define IDD_SETTING_DIALOG              138
#define IDR_CONNECTING                  139
#define IDB_COMPUTER                    141
#define IDD_PROGRESS_DIALOG             173
#define IDD_CONNECTING_STATUS           174
#define IDC_STATIC_MATRIX               1000
#define IDC_STATIC_FONT                 1001
#define IDC_BUTTON_CONVERT              1009
#define IDC_BUTTON_LOAD                 1010
#define IDC_BUTTON_CLEAR                1010
#define IDC_EDIT_TEXT                   1011
#define IDC_BUTTON1                     1012
#define IDC_BUTTON_START                1012
#define IDC_BUTTON2                     1013
#define IDC_BUTTON_STOP                 1013
#define IDC_EDIT_TEXT_STATIC            1014
#define IDC_EDIT_RATE                   1015
#define IDC_SPIN_RATE                   1016
#define IDC_BUTTON_CLEAK_BK             1017
#define IDC_COMBO_SCROLL_MODE           1018
#define IDC_EDIT_TOPBOT                 1019
#define IDC_COMBO_LINE_INDEX            1019
#define IDC_SPIN_TOPBOT                 1020
#define IDC_EDIT_LEFTRIGHT              1021
#define IDC_SPIN_LEFTRIGHT              1022
#define IDC_EDIT_TOPBOT_TEXT            1023
#define IDC_SPIN_TOPBOT_TEXT            1024
#define IDC_EDIT_LEFTRIGHT_TEXT         1025
#define IDC_SPIN_LEFTRIGHT_TEXT         1026
#define IDC_BUTTON_LOAD_TEXT            1027
#define IDC_BUTTON_LOAD_TEXT_STATIC     1028
#define IDC_LIST_LAYER                  1030
#define IDC_COMBO_COLOR                 1031
#define IDC_COMBO_COLOR_TEXT            1032
#define IDC_ANIMATE                     1032
#define IDC_BUTTON_MERGE                1033
#define IDC_CHECK_LAYER0                1034
#define IDC_STATIC_TEXT                 1035
#define IDC_CHECK_LAYER1                1035
#define IDC_CHECK_LAYER2                1036
#define IDC_CHECK_LAYER3                1037
#define IDC_CHECK_LAYER_BK              1038
#define IDC_STATIC_COM_STATUS           1039
#define IDC_STATIC_CLOCK                1040
#define IDC_STATIC_FRAME                1041
#define IDC_COMBO_COMPORT               1044
#define IDC_EDIT_COLUMN                 1045
#define IDC_SPIN_COLUMN                 1046
#define IDC_COMBO_ROW                   1047
#define IDC_COMBO_RESIZE                1048
#define IDC_CHECK_SAVE_AFTER_LOAD       1051
#define IDC_CHECK_GRADIENT_TEXT         1052
#define IDC_CHECK_GRADIENT_BK           1053
#define IDC_COMBO_FONT                  1054
#define IDC_COMBO_FONT_BK               1055
#define IDC_STATIC_FONT_TEXT            1055
#define IDC_STATIC_FONT_BK              1056
#define IDC_LIST_FONT                   1057
#define IDC_BUTTON_SET                  1058
#define IDC_CHECK_ADJUST                1059
#define IDC_PROGRESS                    1060
#define IDC_STATIC_PROGRESS             1061
#define ID_DEVICE_DOWNLOADDATA          32771
#define ID_DEVICE_DOWLOADSTATICTEXT     32772
#define ID_POPUP_LOADBACKGROUNDIMAGE    32777
#define ID_POPUP_LOADFRAMESIMAGE        32778
#define ID_POPUP_OPENWORKSPACE          32779
#define ID_POPUP_SAVEWORKSPACE          32780
#define ID_FILE_OPENWORKSPACE           32781
#define ID_FILE_SAVEWORKSPACE           32782
#define ID_FILE_EXIT                    32783
#define ID_HELP_ABOUT                   32784
#define ID_OPTION_SETTINGS              32785
#define ID_POPUP_CHANGESCALE_1X1        32786
#define ID_POPUP_CHANGESCALE_2X2        32787
#define ID_POPUP_CHANGESCALE_3X3        32788
#define ID_POPUP_CHANGESCALE_4X4        32789
#define ID_DEVICE_STARTSCROLL           32790
#define ID_DEVICE_STOPSCROLL            32791
#define ID_POPUP_STARTSCROLL            32792
#define ID_POPUP_STOPSCROLL             32793
#define ID_DEVICE_SAVETEXTTOEEPROM      32794
#define ID_DEVICE_LOADTEXTFROMEEPROM    32795
#define ID_DEVICE_SAVEBACKGROUNDTOEEPROM 32796
#define ID_DEVICE_LOADBACKGROUNDFROMEEPROM 32797
#define ID_DEVICE_POWEROFF              32798
#define ID_DEVICE_POWERONCOMMAND        32799
#define ID_DEVICE_SAVEALLDATATOEEPROM   32800
#define ID_DEVICE_LOADALLDATAFROMEEPROM 32801
#define ID_DEVICE_RESTOREFACTORYSETTINGS 32802
#define ID_DEVICE_SETDEVICEDATETIME     32803
#define ID_DEVICE_STANDBYSETTING        32804
#define ID_DEVICE_DOWNLOADBUILDINCHARACTERFONT 32805
#define ID_DEVICE_SAVEBUILDINCHARACTERFONTTOEEPROM 32806
#define ID_DEVICE_LOADBUILDINCHARACTERFONTFROMEEPROM 32807
#define ID_DEVICE_LOADASCIITEXTUSINGEMBEDEDFONT 32808
#define ID_OPTION_FONTFIREEDITOR        32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
